version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    container_name: elasticsearch
    ports:
      - ${ELASTICSEARCH_API_PORT}:9200
      - ${ELASTICSEARCH_CLUSTER_PORT}:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata:/usr/share/elasticsearch/data