version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.4
    restart: always
    container_name: elasticsearch
    ports:
      - ${ELASTICSEARCH_API_PORT}:9200
      - ${ELASTICSEARCH_CLUSTER_PORT}:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./esdata:/usr/share/elasticsearch/data